### ISSUE TITLE
post_detail method in views.py in chap2 not working with year/month/day format!

### ISSUE THREAD

**Issue by pichlou** [guinslym/django-by-example-book#1]

**Comment by pichlou** [comment]
post detail is not found with current format of example in chapter 2.
i am using this format for access post detail 

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published')
    return render(request,
                  'blog/post/detail.html',
                  {'post': post})

**Comment by guinslym** [comment]
hi @pichlou what is the page in the chapter 2 that that you are in? There is a difference between 'post detail is not found' and your function 'post_detail'. You might need to check your urls.py for spellcheck on the 'post_detail'
