### ISSUE TITLE
How Profile model instance will create when user Login via social account ?

### ISSUE THREAD

**Issue by hiteshgarg14** [guinslym/django-by-example-book#3]
As we included `profile = Profile.objects.create(user=new_user)` in register view.

**Comment by guinslym** [comment]
Hi @hiteshgarg14 I don't know which page your are in right now.  Each time a user will click the button to register. Django will process the request with this function found in account/views.py
`profile = Profile.objects.create(user=new_user)`

```
def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                    user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            return render(request,
                    'account/register_done.html',
                    {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
return render(request,'account/register.html',{'user_form': user_form})
```
As you cans see if the **form** is valid then let's create a **User** and also a **Profile** for this **User**

**Comment by hiteshgarg14** [comment]
@guinslym i am talking about `Adding social authentication to your site` section on page 122. your above code is right. but my concern is how `Profile` object will create when user singup using facebook or google or twitter ?

**Comment by guinslym** [comment]
hi @hiteshgarg14 it still the same process. `python-social-auth` is acting as an Authentification method. Meaning that the first time a **User** will signup using social auth, the `python-social-auth` package will serve somehow as the same thing as if the user has put his **email** and **password**  then the app will **still** go to the **register** __View__ to register the **User** and create a **Profile**.
