### ISSUE TITLE
I get a 404 page

### ISSUE THREAD

**Issue by noelvillaman** [guinslym/django-by-example-book#4]
Hi, 

I was wondering if you can help me. I am going through this book, and after I get my posts and display them on the screen I cannot see the detail page. I get a 404. I checked your code and It is the same as mine. Did you have such a problem?

NOel.

**Comment by noelvillaman** [comment]
Request Method:	GET
Request URL:	http://localhost:3025/blog/2017/02/07/linux-threads-vs-windows-threads/
Raised by:	blog.views.post_detail

**Comment by askovvur** [comment]
I'm getting a similar problem. But instead of a 404, I am being redirected to the post_list page every time.

**Comment by noelvillaman** [comment]
I decided to to for the slug only
localhost:80000/blog/media-analysis-paper/ and change the url patterns to
only that. So also in my get_absolute_url method to get only the slug.

**Comment by guinslym** [comment]
Hi @noelvillaman! I haven't got the same errors as yours and I still don't. On [my project code](https://github.com/guinslym/django-by-example-book/tree/master/chap_1_blog/mysite) I can access this url [http://127.0.0.1:8000/blog/2016/04/17/sunt-recusandae-quo-consequatur-corporis-non-temporibus-eaque/](http://127.0.0.1:8000/blog/2016/04/17/sunt-recusandae-quo-consequatur-corporis-non-temporibus-eaque/) without having a 404

models.py
```
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])
````
views.py
```
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})
```
templates
`<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>`

**Comment by ozza** [comment]
I think it's about the internationalization settings. If I change to TIME_ZONE to Europe/Athens-Moscow-Istanbul etc.. from UTC I'm getting a 404 error as well. You can check for this too.
