### ISSUE TITLE
post detail

### ISSUE THREAD

**Issue by ghost** [guinslym/django-by-example-book#5]
hello
in chapter 1
my post detail page not working, when I click on a post, it cant enter post detail page!

**Comment by guinslym** [comment]
hi @DjawadT! 
Please use https://www.packtpub.com/web-development/django-example for asking questions. I don't see your code I don't know what you did wrong. I would suggest that you try the Django tutorial. It's a simple tutorial and it's easier than the chapter 1 in Antonio Mele's book.
