### ISSUE TITLE
Rendering template without passing data to it

### ISSUE THREAD

**Issue by olekthunder** [guinslym/django-by-example-book#6]
## mysite/blog/views.py
post_share function renders blog/post/share.html without passing "cd" value to template

```python
return render(request, 'blog/post/share.html', {'post':post, 'form': form, 'sent': sent})
```

## mysite/blog/templates/blog/post/share.html
While template expects to get it
```html
{% if sent %}
     <h1>E-mail successfully sent</h1>
     <p>
         "{{ post.title }}" was successfully sent to {{cd.to}}.
     </p>
{% else %}
```

**Comment by guinslym** [comment]
Thanks @CodyBranner! I corrected it. I added a `recipient` variable.

(Chapter 2) mysite/blog/views.py ---def post_share(...)

```
            ...
            #Get the recipient email
            recipient=cd['to']
            sent = True
    else:
        form = EmailPostForm()
        recipient=False
    return render(request, 'blog/post/share.html', 
                    {
                        'post':post, 
                        'form': form, 
                        'sent': sent, 
                        'recipient': recipient
                    }
                )
```

(chapter 2) mysite/blog/templates/blog/post/share.html
`"{{ post.title }}" was successfully sent to {{recipient}}.`

But on the code example they don't have this variable on their Template so no need to alternate the views.py. 
Django_By_Example_Code/Chapter 2/mysite/blog/templates/blog/post/share.html
` <p>"{{ post.title }}" was successfully sent by e-mail.</p>`
