### ISSUE TITLE
Problem with chapter 8, PayPal

### ISSUE THREAD

**Issue by moreplavec** [guinslym/django-by-example-book#8]
I tried to run chapter 8 and it works fine after installing all requirements into virtual enviroment. But if i try to pay with Paypal, it hangs. It redirects to PayPal sandbox,https://www.sandbox.paypal.com/cgi-bin/webscr, but nothing shows and nothing happens. Any tip what is wrong? 

I'm running up-to-date django and python, but i think this is some PayPal issue?

**Comment by guinslym** [comment]
Hi @moreplavec I couldn't reproduce your error. So I think it was due to paypal. You could watch this video to see how to integrate Paypal to Django

[https://www.youtube.com/watch?v=Z5dBopZWOzo](https://www.youtube.com/watch?v=Z5dBopZWOzo)
