### ISSUE TITLE
Not an issue with the code, just the text

### ISSUE THREAD

**Issue by ldmcdaniel** [guinslym/django-by-example-book#9]
When you say to `pip install django-taggit==0.17.1` in Adding tagging functionality of Chapter 2, this version did not work for me, it seems because there is a conflict with Django 1.9.  I needed to use a [different version](https://github.com/alex/django-taggit/blob/master/CHANGELOG.txt), so I chose `0.17.6` and it worked perfectly.  The book is great and I am learning a lot.  Thanks for taking the time to write it!  If I should put this comment in another place, please let me know and I will.

Kind regards!

**Comment by guinslym** [comment]
hi @ldmcdaniel ! Thanks for your comment the folder titled `Django_By_Example_Code` contains the code source of the book without a `requirements.txt` file so you can read the book and install the version of a package that fit your configuration. I didn't wrote this book. This book is really great!!! To send a comment to the author I believe you can google for Antonio Melé to look for his contact online or you can direct send a message to Packtub Publisher. Also recently Lynda.com have added the video of the book content. Meaning that Antonio Melé do each Chapter of the book. So you can login/subscribe to Lynda.com and follow the video provide by Antonio Mélé. 

Regards,
Guinsly M.
